import redis
import json
import os
import uuid as uuid_lib
from datetime import datetime
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from cryptography.fernet import Fernet
import base64

from logger import get_logger
logger = get_logger("history")

app = FastAPI(title="History Service")

# CORS POLICY — DEVELOPMENT ONLY
# Cross-Origin Resource Sharing (CORS) controls which domains are allowed to make
# requests to this API.
# (allow_origins=["*"]) is intentionally permissive to allow the frontend to communicate
#  with the backend during local development.
#
# WARNING: This must not be used in production. In a production environment, this should
# be restricted to the specific domain serving the frontend, and validated by a security
# expert before any deployment.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

#NOTE history has its own redis db file so there can be no data corruption by other services
# it validates the separation of concerns principles of microservice architecture
#NOTE Default points to the redis-history container name as defined in docker-compose for dev purpose.
# Change this to the actual host if deploying outside of Docker Compose.
r = redis.Redis(host=os.getenv("REDIS_HOST", "redis-history"), port=6379, decode_responses=True)

# Fernet requires a 32-byte url-safe base64-encoded key.
# We derive it from the ESTIMATE_ENCRYPTION_KEY env variable generated by the CLI.
raw_key = os.getenv("ESTIMATE_ENCRYPTION_KEY", "")
fernet = Fernet(base64.urlsafe_b64encode(bytes.fromhex(raw_key))) if raw_key else None


class Estimate(BaseModel):
    username: str
    input: dict
    result: dict
    estimate_name: str = ""


@app.post("/estimates")
def save_estimate(estimate: Estimate):
    estimate_id = str(uuid_lib.uuid4())
    logger.info("Estimate saved for user: %s — id: %s", estimate.username, estimate_id)

    # Encrypt the estimate name before storage — it may contain sensitive information
    # such as a property address. A separate key from auth ensures that a breach of one
    # datastore does not compromise the other.
    encrypted_name = ""
    if fernet and estimate.estimate_name:
        encrypted_name = fernet.encrypt(estimate.estimate_name.encode()).decode()

    entry = {
        "id": estimate_id,
        "input": estimate.input,
        "result": estimate.result,
        "estimate_name": encrypted_name,
        "timestamp": datetime.now().isoformat()
    }
    r.set(f"estimate:{estimate.username}:{estimate_id}", json.dumps(entry))
    # A sorted set is used instead of a plain list because it keeps estimates ordered by
    # timestamp natively, without requiring a sort at read time.
    r.zadd(f"estimates:{estimate.username}", {estimate_id: datetime.now().timestamp()})
    return {"id": estimate_id}


def _decrypt_name(encrypted_name: str, username: str) -> str:
    # Decrypt the estimate name for display — only possible with the correct key
    if fernet and encrypted_name:
        try:
            return fernet.decrypt(encrypted_name.encode()).decode()
        except Exception as e:
            logger.warning("Failed to decrypt estimate name for user %s: %s", username, e)
            return ""
    return ""


@app.get("/estimates/{username}")
def get_estimates(username: str):
    estimate_ids = r.zrevrange(f"estimates:{username}", 0, 49)
    estimates = []
    for eid in estimate_ids:
        raw = r.get(f"estimate:{username}:{eid}")
        if raw:
            entry = json.loads(raw)
            entry["estimate_name"] = _decrypt_name(entry.get("estimate_name", ""), username)
            estimates.append(entry)
    logger.info("History fetched for user: %s — %d estimates returned", username, len(estimates))
    return {"history": estimates}


@app.get("/estimates/{username}/{estimate_id}")
def get_estimate(username: str, estimate_id: str):
    raw = r.get(f"estimate:{username}:{estimate_id}")
    if not raw:
        raise HTTPException(status_code=404, detail="Estimate not found.")
    entry = json.loads(raw)
    entry["estimate_name"] = _decrypt_name(entry.get("estimate_name", ""), username)
    return entry